### ISSUE TITLE
Screen "designs"

### ISSUE THREAD

**Issue by goyozi** [codebar/pairing-tool#1]
All of our further work needs some basic screen designs so that we can focus on the implementation part. We're going to have a short whiteboarding session and then nominate someone to prepare the "designs".

**Comment by jmbriano** [comment]
I'm interested in this activity. Can you let me know when it is planned?

**Comment by goyozi** [comment]
You’re kind of lucky with this one 😀 the session was supposed to happen this week but my epic calendar skills have failed, so it’s probably going to happen first thing after New Year’s break (both me and Marina are coming back on the 7th). Not sure if doing this online some time before is an option?
