### ISSUE TITLE
Create a new "coach" entry to the participant list.

### ISSUE THREAD

**Issue by GMELIOT** [codebar/pairing-tool#13]
As an organiser I want to be able to add a new coach to the list so that, if the coach didn't sign up, they can still be added to the pairing process.

**Comment by jmbriano** [comment]
@GMELIOT I had a quick look to the branch for this issue. Would it be possible to only have 1 field where we can add the whole string together (inlcuding name(s) lastaname(s))?
When importing from the txt will not be able to distinguish what is first name, and what is last name. 

Also, using a single field for both is more inclusive (we are very used to the existance of first name and last name, but not every culture does this distinction. Neither it is mandatory to have both when registering to codebar as far as I remember)
